# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name: 'ksaitor'
description: 'Essays on tech, startups, music, Singapore and other curious observations in life'
author:
  name: Raman Shalupau
  twitter: ksaitor
  github: ksaitor
  linkedin: ramanshalupau
  soundcloud: ksaitor
  instagram: ksaitor
  youtube: https://www.youtube.com/channel/UCPr3svxWJzJuog9R_-tKOUw

copyright:
  year: 2025
  name: ksaitor

# Google Analytics 4 — replace G-XXXXXXXXXX with your GA4 measurement ID
google-analytics:
  id: G-XXXXXXXXXX

# Disqus
disqus:
  id: ksaitor

# RRSSB Social Sharing
rrssb:
  facebook: true
  twitter: true
  pocket: true
  email: false
  linkedin: true
  reddit: false
  hackernews: true
  pinterest: false
  googleplus: false
  tumblr: false

# SEO
title: 'ksaitor — essays on tech, startups & life'
twitter:
  card: 'summary_large_image'
  username: 'ksaitor'

# URL
url: 'https://ksaitor.com' # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl: '' # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Singapore
permalink: /:year-:month-:day/:title/

# Pagination
paginate: 5
paginate_path: /page:num/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Navigation
nav:
  - name: 'Archive'
    url: '/archive'
  - name: 'Twitter'
    url: 'https://twitter.com/ksaitor'

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Scopes
defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      share_buttons: true
  - scope:
      path: '/admin/'
    values:
      sitemap: false

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-minifier

exclude: [vendor]

jekyll-minifier:
  uglifier_args:
    harmony: true
